stages:
  - make_assets
  - prepare_view
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

# Static data to describe how source files compose the labs
# Each entry will be named lab1.md, lab2.md, etc.
lab_structure:
  - title: Lab 1 - Operating System Perspective
    filename: lab1.md
    content:
      - tasks/basic-syscall.md
      - tasks/syscall-wrapper.md
      - tasks/libcall-syscall.md
      - reading/modern-sw-stack.md
      - reading/basic-syscall.md
      - reading/syscall-wrapper.md
      - reading/libcall-syscall.md
  - title: Lab 2 - Library Perspective
    filename: lab2.md
    content:
      - tasks/common-functions.md
      - tasks/libc.md
      - tasks/high-level-lang.md
      - tasks/app-investigation.md
      - guides/static-dynamic.md
      - reading/common-functions.md
      - reading/libc.md
      - reading/high-level-lang.md
      - reading/app-investigate.md
  - title: Lab 3 - Memory
    filename: lab3.md
    content:
      - tasks/memory-access.md
      - tasks/memory-corruption.md
      - tasks/memory-protection.md
      - tasks/access-counter.md
      - reading/working-with-memory.md
      - reading/process-memory.md
      - guides/memory-alloc.md
      - guides/memory-vuln.md
  - title: Lab 4 - Investigate Memory
    filename: lab4.md
    content:
      - tasks/alloc-size.md
      - tasks/copy.md
      - tasks/memory-areas.md
      - tasks/modify-areas.md
      - tasks/static-dynamic.md
      - tasks/page-mapper.md
      - tasks/reference-counting.md
      - reading/investigate-memory.md
      - guides/app-investigation-deluge.md
      - guides/app-investigation-servo.md
      - guides/d-allocator.md
      - guides/git.md
      - guides/jemalloc.md
      - guides/memory-actions.md
      - guides/memory-leak.md
  - title: Lab 5 - Memory Security
    filename: lab5.md
    content:
      - tasks/pointer-arithmetic-leak.md
      - tasks/aslr.md
      - tasks/stack-protector.md
      - tasks/bypassing-stack-protector.md
      - tasks/exec-shellcode.md
      - reading/memory-security.md
      - guides/buffer-overflow-leak.md
      - guides/buffer-overflow-overwrite.md
  - title: Lab 6 - Multiprocess and Multithread
    filename: lab6.md
    content:
      - tasks/sleepy.md
      - tasks/wait-for-me-processes.md
      - tasks/create-process.md
      - tasks/multithreaded.md
      - tasks/sum-array.md
      - tasks/sum-array-bugs.md
      - reading/hardware-perspective.md
      - reading/processes.md
      - reading/threads.md
      - guides/create-process.md
      - guides/sum-array-processes.md
      - guides/system-dissected.md
      - guides/sum-array-threads.md
      # - guides/wait-for-me-threads.md
      - guides/clone.md
  - title: Lab 7 - Copy-on-Write
    filename: lab7.md
    content:
      - tasks/page-faults.md
      - tasks/mini-shell.md
      - tasks/apache2.md
      - tasks/shared-memory.md
      - reading/processes-threads-apache2.md
      - reading/copy-on-write.md
      - guides/apache2.md
      - guides/fork-faults.md
  - title: Lab 8 - Syncronization
    filename: lab8.md
    content:
      - tasks/race-condition.md
      - tasks/wrap-the-for.md
      - tasks/race-condition-atomic.md
      - tasks/tls-on-demand.md
      - tasks/atomic-assembly.md
      - guides/apache2-simulator-semaphore.md
      - tasks/apache2-simulator-condition.md
      - reading/synchronization.md
      - reading/user-level-threads.md
      - reading/scheduling.md
      - guides/user-level-threads.md
      - guides/libult.md
  - title: Lab 9 - File Descriptors
    filename: lab9.md
    content:
      - tasks/my-cat.md
      - tasks/mmap_cp.md
      - tasks/anon-pipes.md
      - reading/file-descriptors.md
      - reading/fd-operations.md
      - reading/pipes.md
      - guides/simple-file-operations.md
      - guides/redirections.md
      - guides/fd-table.md
      - guides/libc-FILE-struct.md
      - guides/file-mappings.md
      - guides/reading-linux-dirs.md
  - title: Lab 10 - Inter-Process Communication
    filename: lab10.md
    content:
      - tasks/named-pipes.md
      - tasks/unix-socket.md
      - tasks/network-socket.md
      - tasks/receive-challenges.md
      - reading/unix-sockets.md
      - reading/network-sockets.md
      - reading/client-server-model.md
      - guides/networking-101.md
  - title: Lab 11 - IO Optimizations
    filename: lab11.md
    content:
      - tasks/client-server.md
      - tasks/multiplexed-client-server.md
      - tasks/async-server.md
      - reading/io-multiplexing.md
      - reading/async-io.md
      - reading/zero-copy.md
      - guides/benchmarking-sendfile.md
      - guides/kernel-caching.md
      - guides/async.md
  - title: Lab 12 - Application Interaction
    filename: lab12.md
    content:
      - tasks/time-server.md
      - tasks/password-cracker.md
      - tasks/dbus.md
      - reading/x-window-system.md
      - reading/time-server.md
      - reading/password-cracker.md
      - guides/containers-vs-vms.md
      - reading/os-cloud.md
      - reading/dbus.md
      - guides/dbus-dfeet.md
      - guides/calling-dbus-methods.md
      - guides/inspecting-low-level-communication.md
      - guides/dbus-usage-python.md
      - guides/firefox.md
make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/software-stack
      - chapters/data
      - chapters/compute
      - chapters/io
      - chapters/app-interact
    args:
      - all

prepare_view:
  plugin: command
  options:
    command: python
    locations:
      - .
    args:
      - gen-view.py

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      Software-Stack: slides/Software-Stack
      Data: slides/Data
      Compute: slides/Compute
      IO: slides/IO
      Application-Interaction: slides/Application-Interaction

docusaurus:
  plugin: docusaurus
  options:
    course_name: SO
    sidebar: js
    structure:
      - Introduction: landing-page/README.md
      - Setting up the Lab Environment: misc/lab-setup.md
      - Software Stack:
          path: /build/prepare_view/.view
          extra:
            - media
          subsections:
            - Slides: /build/embed_reveal/Software-Stack/Software-Stack.mdx
            - Overview: /build/prepare_view/.view/software-stack-overview.md
            - Questions:
                path: questions
                subsections:
                  - Printf vs Write: printf-vs-write.md
                  - Syscall ID: syscall-id.md
                  - Python Tools: python-tools.md
                  - Malloc: malloc.md
                  - Software: software.md
                  - Static Executables: static-executables.md
                  - Syscall Numbers: syscall-numbers.md
                  - Printf Syscall: printf-syscall.md
                  - Syscall Wrapper: syscall-wrapper.md
                  - Syscall Tool: syscall-tool.md
                  - Libcall Syscall: libcall-syscall.md
                  - Libc: libc.md
                  - Dynamic Libraries: dynamic-libraries.md
                  - Strcpy Syscall: strcpy-syscall.md
            - Lab 1 - Operating System Perspective: lab1.md
            - Lab 2 - Library Perspective: lab2.md
      - Data:
          path: /build/prepare_view/.view
          extra:
            - media
          subsections:
            - Slides: /build/embed_reveal/Data/Data.mdx
            - Overview: /build/prepare_view/.view/data-overview.md
            - Questions:
                path: questions
                subsections:
                  - Memory Access: memory-access.md
                  - Half page: half-page.md
                  - Malloc Brk: malloc-brk.md
                  - Malloc Mmap: malloc-mmap.md
                  - Memory granularity: memory-granularity.md
                  - Mmap file: mmap-file.md
                  - Page Allocation: page-allocation.md
                  - Operators: operators.md
                  - Memory Leaks: memory-leaks.md
                  - Valgrind Leaks: valgrind-leaks.md
                  - Bypass Canary: bypass-canary.md
                  - Memory Aslr: memory-aslr.md
                  - Memory Regions Vars: memory-regions-vars.md
                  - Memory Stack Protector: memory-stack-protector.md
                  - Stack Layout: stack-layout.md
                  - String buff over: string-buff-over.md
                  - String strcpy: string-strcpy.md
            - Lab 3 - Memory: lab3.md
            - Lab 4 - Investigate Memory: lab4.md
            - Lab 5 - Memory Security: lab5.md
      - Compute:
          path: /build/prepare_view/.view
          extra:
            - media
          subsections:
            - Slides: /build/embed_reveal/Compute/Compute.mdx
            - Overview: /build/prepare_view/.view/compute-overview.md
            - Questions:
                path: questions
                subsections:
                  - Parent Faults Before Fork: parent-faults-before-fork.md
                  - Mmap Cow Flag: mmap-cow-flag.md
                  - Sections Always Shared: sections-always-shared.md
                  - Child Faults After Write: child-faults-after-write.md
                  - Seg Fault Exit Code: seg-fault-exit-code.md
                  - Threads Shared Data: threads-shared-data.md
                  - Thread Memory: thread-memory.md
                  - Apache2 Strace: apache2-strace.md
                  - Mini Shell Stops After Command: mini-shell-stops-after-command.md
                  - Cause of File Not Found Error: cause-of-file-not-found-error.md
                  - Process Creation: process-creation.md
                  - Who Calls Execve Parent: who-calls-execve-parent.md
                  - Exec Without Fork: exec-without-fork.md
                  - Create Sleepy Process Ending: create-sleepy-process-ending.md
                  - Processes Speedup: processes-speedup.md
                  - Parent of Sleep Processes: parent-of-sleep-processes.md
                  - Sleeping on a Fiber: sleeping-on-a-fiber.md
                  - Fiber Strace: fiber-strace.md
                  - Type of Scheduler in Libult: type-of-scheduler-in-libult.md
                  - Number of Running Ults: number-of-running-ults.md
                  - Why Use Completed Queue: why-use-completed-queue.md
                  - Ult Thread IDs: ult-thread-ids.md
                  - TCB Libult Unikraft: tcb-libult-unikraft.md
                  - Time Slice Value: time-slice-value.md
                  - Number of Running Threads: number-of-running-threads.md
                  - Notify Only With Mutex: notify-only-with-mutex.md
                  - TLS Var Copies: tls-var-copies.md
                  - TLS Synchronization: tls-synchronization.md
                  - Semaphore Equivalent: semaphore-equivalent.md
                  - Coarse vs Granular Critical Section: coarse-vs-granular-critical-section.md
                  - Not Race Condition: not-race-condition.md
            - Lab 6 - Multiprocess and Multithread: lab6.md
            - Lab 7 - Copy-on-Write: lab7.md
            - Lab 8 - Syncronization: lab8.md
      - IO:
          path: /build/prepare_view/.view
          extra:
            - media
          subsections:
            - Slides: /build/embed_reveal/IO/IO.mdx
            - Overview: /build/prepare_view/.view/io-overview.md
            - Questions:
                path: questions
                subsections:
                  - Bind Error Cause: bind-error-cause.md
                  - Anonymous Pipes Limitation: anonymous-pipes-limitation.md
                  - Pipe Ends: pipe-ends.md
                  - Receiver Socket FD: receiver-socket-fd.md
                  - Client Server Sender Receiver: client-server-sender-receiver.md
                  - Firefox TCP UDP: firefox-tcp-udp.md
                  - Server Copies: server-copies.md
                  - Fewer Than 2 Copies: fewer-than-2-copies.md
                  - Strace Printf: strace-printf.md
                  - Mmap Read Write Benchmark: mmap-read-write-benchmark.md
                  - Syscalls CP: syscalls-cp.md
                  - File Handler C: file-handler-c.md
                  - Flush Libc Buffer: flush-libc-buffer.md
                  - Stderr FD: stderr-fd.md
                  - Local IO Errors: local-io-errors.md
                  - Fopen Syscall: fopen-syscall.md
            - Lab 9 - File Descriptors: lab9.md
            - Lab 10 - Inter-Process Communication: lab10.md
            - Lab 11 - IO Optimizations: lab11.md
      - Application Interaction:
          path: /build/prepare_view/.view
          extra:
            - media
          subsections:
            - Slides: /build/embed_reveal/Application-Interaction/Application-Interaction.mdx
            - Overview: /build/prepare_view/.view/app-interact-overview.md
            - Questions:
                path: questions
                subsections:
                  - Time Server: time-server.md
                  - Time Server Interop: time-server-interop.md
                  - X Window System: timer.md
                  - Vm Creation: vm-creation.md
                  - Container versus VM: container-vs-vm.md
                  - Cgroups versus namespaces: cgroups-vs-namespaces.md
            - Lab 12 - Application Interaction: lab12.md
      - Assignments:
          # These all have the same filename so we need to create separate
          # subdirectories for them, otherwise they will overwrite each other.
          # (See the trailing slash in the path.)
          subsections:
            - Mini Libc/: chapters/software-stack/libc/projects/mini-libc/
            - Memory Allocator/: content/assignments/memory-allocator/
            - Parallel Firewall/: content/assignments/parallel-firewall/
            - Mini Shell/: content/assignments/minishell/
            - Asynchronous Web Server/: content/assignments/async-web-server/
      - Exams:
          path: chapters/general/drills/tasks
          subsections:
            - 2024 Summer:
                subsections:
                  - Syscall Tracing/: syscall-tracing.md
                  - Sysinfo Library/: sysinfo-library.md
            - Digital Forensics/: digital-forensics.md
            - Distributed System/: distributed-system.md
            - Aggregator Application/: aggregator-application.md
            - Benchmarking Application/: benchmarking-application.md
            - Database Application/: database-application.md
            - Application Investigator/: application-investigator.md
            - Network Performance Utility/: network-performance-utility.md
            - Nightly Builds System/: nightly-builds-system.md
            - User-level Threading Library/: user-level-threading-library.md
            - System Process Monitoring Tool/: system-process-monitoring-tool.md
            - Network Configurations Manager/: network-configurations-manager.md
            - FaaS Application/: faas-application.md
            - Industrial System/: industrial-system.md
            - Blockchain System/: blockchain-system.md
            - Supervisor-type Service/: supervisor-type-service.md
            - Header Analysis Application/: header-analysis-application.md
            - Extending an App Manager/: extending-an-app-manager.md
            - Backup System/: backup-system.md
            - File Changes Notifier/: file-changes-notifier.md
            - Intrusion Detection System/: intrusion-detection-system.md
            - Resource Monitor/: resource-monitor.md
            - Library Warmer/: library-warmer.md
            - Web GUI 1/: web-gui-1.md
            - Web GUI 2/: web-gui-2.md
            - Memory Deduplication/: memory-deduplication.md
            - Cloud System/: cloud-system.md
      - Hackathons:
          path: content/assignments
          subsections:
            - Lambda Function Loader/: lambda-function-loader/
      - Rules and Grading: misc/rules-and-grading.md
      - Resources: misc/resources.md
    static_assets:
      - slides/Compute: /build/make_assets/chapters/compute/_site
      - slides/Data: /build/make_assets/chapters/data/_site
      - slides/Software-Stack: /build/make_assets/chapters/software-stack/_site
      - slides/IO: /build/make_assets/chapters/io/_site
      - slides/Application-Interaction: /build/make_assets/chapters/app-interact/_site
    config_meta:
      title: Operating Systems
      url: http://localhost/
      baseUrl: /operating-systems/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://curs.upb.ro
      OCW: https://ocw.cs.pub.ro/courses/so
      Facebook: https://www.facebook.com/sisteme.de.operare/
    copyright_string: SO Team
